export type ShopProduct = {
  slug: string;
  title: string;
  price: number;
  color: string;
  description?: string;
  images?: string[];
};

export const SHOP_PRODUCTS: ShopProduct[] = [
  // Pottery (Kvido Pottery placeholders)
  {
    slug: "ceramic-mug-1",
    title: "Ceramic Mug - Kvido 1",
    price: 28,
    color: "#A8D8EA",
    description: "Handcrafted Kvido pottery mug with a smooth glaze.",
    images: ["/images/cup1.png", "/images/cup3.png"],
  },
  {
    slug: "ceramic-bowl-1",
    title: "Ceramic Bowl - Kvido 2",
    price: 35,
    color: "#FCBAD3",
    description: "Beautiful Kvido serving bowl perfect for any table.",
    images: ["/images/cup4.png", "/images/cup5.png"],
  },
  {
    slug: "ceramic-plate-1",
    title: "Ceramic Plate - Kvido 3",
    price: 32,
    color: "#B5EAD7",
    description: "Durable Kvido plate with elegant design.",
    images: ["/images/cup3.png", "/images/cup1.png"],
  },
  {
    slug: "ceramic-vase-1",
    title: "Ceramic Vase - Kvido 4",
    price: 42,
    color: "#E0BBE4",
    description: "Sculptural Kvido vase for dried flowers or display.",
    images: ["/images/cup4.png", "/images/cup2.png"],
  },
  {
    slug: "ceramic-mug-2",
    title: "Ceramic Mug - Kvido 5",
    price: 28,
    color: "#FFE0B2",
    description: "Warm Kvido pottery mug in earthy tones.",
    images: ["/images/cup5.png", "/images/cup6.png"],
  },
  {
    slug: "ceramic-bowl-2",
    title: "Ceramic Bowl - Kvido 6",
    price: 35,
    color: "#73CDCD",
    description: "Minimalist Kvido bowl with subtle texture.",
    images: ["/images/cup6.png", "/images/cup5.png"],
  },
  {
    slug: "ceramic-plate-2",
    title: "Ceramic Plate - Cream",
    price: 32,
    color: "#D4E8A5",
    description: "Neutral ceramic plate versatile for any setting.",
    images: ["#D4E8A5", "#E8D4A5", "#E8B4D4"],
  },
  {
    slug: "ceramic-vase-2",
    title: "Ceramic Vase - Terracotta",
    price: 45,
    color: "#C9ADA7",
    description: "Rustic terracotta vase with modern lines.",
    images: ["#C9ADA7", "#D4A5A5", "#D9A5B5"],
  },
  {
    slug: "ceramic-mug-3",
    title: "Ceramic Mug - Sage",
    price: 28,
    color: "#A5E8D4",
    description: "Soothing sage green ceramic mug.",
    images: ["#A5E8D4", "#D4E8A5", "#E8D4A5"],
  },
  {
    slug: "ceramic-bowl-3",
    title: "Ceramic Bowl - Blush",
    price: 38,
    color: "#FFB3BA",
    description: "Delicate pink bowl perfect for desserts.",
    images: ["#FFB3BA", "#FFCCCB", "#FFE0B2"],
  },
  {
    slug: "ceramic-plate-3",
    title: "Ceramic Plate - Sage",
    price: 32,
    color: "#AA96DA",
    description: "Sophisticated sage plate for dining.",
    images: ["#AA96DA", "#FCBAD3", "#F8B4D4"],
  },
  {
    slug: "ceramic-vase-3",
    title: "Ceramic Vase - Blush",
    price: 48,
    color: "#E8B4D4",
    description: "Elegant blush vase for flower arrangements.",
    images: ["#E8B4D4", "#D4A5E8", "#B4D4E8"],
  },
  {
    slug: "ceramic-mug-4",
    title: "Ceramic Mug - Ochre",
    price: 28,
    color: "#E8D4A5",
    description: "Warm ochre toned ceramic mug.",
    images: ["#E8D4A5", "#E8B4D4", "#D4A5E8"],
  },
  {
    slug: "ceramic-bowl-4",
    title: "Ceramic Bowl - Ochre",
    price: 35,
    color: "#C5E1A5",
    description: "Cheerful ochre bowl for serving.",
    images: ["#C5E1A5", "#B5EAD7", "#A1D6D6"],
  },
  {
    slug: "ceramic-vase-4",
    title: "Ceramic Vase - Sage",
    price: 50,
    color: "#7FD8D8",
    description: "Modern sage vase with smooth curves.",
    images: ["#7FD8D8", "#73CDCD", "#6BB7D6"],
  },

  // Prints & Art (15 products)
  {
    slug: "print-1",
    title: "Documentary Drawing Print - A3",
    price: 18,
    color: "#E8B4D4",
    description: "Beautiful A3 print of documentary drawing.",
    images: ["#E8B4D4", "#D4A5E8", "#B4D4E8"],
  },
  {
    slug: "print-2",
    title: "Illustration Print - A2",
    price: 24,
    color: "#B5EAD7",
    description: "Vibrant illustration print in A2 size.",
    images: ["#B5EAD7", "#A1D6D6", "#7FD8D8"],
  },
  {
    slug: "print-3",
    title: "Comic Panel Print - A3",
    price: 20,
    color: "#FFB3BA",
    description: "Comic art print in high quality.",
    images: ["#FFB3BA", "#FFCCCB", "#FFE0B2"],
  },
  {
    slug: "print-4",
    title: "Abstract Print - A2",
    price: 25,
    color: "#C9ADA7",
    description: "Modern abstract art print.",
    images: ["#C9ADA7", "#D4A5A5", "#D9A5B5"],
  },
  {
    slug: "print-5",
    title: "Nature Study Print - A3",
    price: 18,
    color: "#A5E8D4",
    description: "Nature inspired A3 print.",
    images: ["#A5E8D4", "#D4E8A5", "#E8D4A5"],
  },
  {
    slug: "print-6",
    title: "Urban Sketch Print - A2",
    price: 26,
    color: "#B4D4E8",
    description: "Architectural sketch print A2.",
    images: ["#B4D4E8", "#A5E8D4", "#D4E8A5"],
  },
  {
    slug: "print-7",
    title: "Character Design Print - A3",
    price: 19,
    color: "#AA96DA",
    description: "Character study print A3.",
    images: ["#AA96DA", "#FCBAD3", "#F8B4D4"],
  },
  {
    slug: "print-8",
    title: "Pattern Print - A2",
    price: 27,
    color: "#73CDCD",
    description: "Decorative pattern print A2.",
    images: ["#73CDCD", "#6BB7D6", "#B5EAD7"],
  },
  {
    slug: "print-9",
    title: "Surreal Print - A3",
    price: 21,
    color: "#E5A5A5",
    description: "Surreal artwork print A3.",
    images: ["#E5A5A5", "#F0A5A5", "#C9ADA7"],
  },
  {
    slug: "print-10",
    title: "River Study Print - A2",
    price: 25,
    color: "#D4A5E8",
    description: "Water landscape print A2.",
    images: ["#D4A5E8", "#B4D4E8", "#A5E8D4"],
  },
  {
    slug: "print-11",
    title: "Editorial Illustration - A3",
    price: 20,
    color: "#FFF9C4",
    description: "Editorial art print A3.",
    images: ["#FFF9C4", "#C5E1A5", "#FFB3BA"],
  },
  {
    slug: "print-12",
    title: "Comic Series Print - A2",
    price: 28,
    color: "#FFCCCB",
    description: "Comic panel collection A2.",
    images: ["#FFCCCB", "#FFE0B2", "#FFF9C4"],
  },
  {
    slug: "print-13",
    title: "Botanical Print - A3",
    price: 19,
    color: "#C5E1A5",
    description: "Botanical study print A3.",
    images: ["#C5E1A5", "#B5EAD7", "#A1D6D6"],
  },
  {
    slug: "print-14",
    title: "Portrait Print - A2",
    price: 26,
    color: "#E0BBE4",
    description: "Portrait study print A2.",
    images: ["#E0BBE4", "#D5B7E4", "#CAB3E4"],
  },
  {
    slug: "print-15",
    title: "Graphic Design Print - A3",
    price: 22,
    color: "#D9A5B5",
    description: "Graphic design print A3.",
    images: ["#D9A5B5", "#E5A5A5", "#F0A5A5"],
  },
];
